name: cipher
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.6.0


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^3.10.0
  google_sign_in: ^6.2.2
  firebase_auth: ^5.4.0
  cloud_firestore: ^5.6.1
  # for store network image
  cached_network_image: ^3.4.1

  flutter_svg: ^2.0.17

  http: ^1.3.0

  image_picker: ^1.1.2
  permission_handler: ^11.3.1
  dio: ^5.8.0+1
  encrypt: ^5.0.3
  saver_gallery: ^4.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.2

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icon/
  #   - images/a_dot_ham.jpeg


flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon.png"

fonts:
    - family: Mulish
      fonts:
        - asset: assets/fonts/Mulish-Light.ttf
        - asset: assets/fonts/Mulish-SemiBold.ttf